[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
NEXT_DISABLE_REACT_COMPILER = "true"
TURBO_DISABLE_TELEMETRY = "1"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "NODE_ENV=production npm run build"

[start]
cmd = "npm start" 