[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build && npx prisma generate"

[start]
cmd = "npx prisma migrate deploy && npm start" 