[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate"]

[start]
cmd = "node index.js" 